canonical/chisel

internal/slicer/slicer.go, internal/slicer/slicer_test.go
If a slice specifies a path /foo/bar/baz, the file is extracted at the 
specified path rooted in the output directory (i.e. out/foo/bar/baz) and 
parent directories are implicitly created. However, since these parent 
directory path are not explicitly specified in selection, the CheckRead 
function fails. Fix it by recording paths including its all parent 
directory paths.
=> slicer: Allow listing implicit parent directories

internal/setup/setup.go, internal/setup/setup_test.go
Turn yamlPath.Text into pointer to distinguish between unset and empty
text attribute of a path. This is mainly to allow setting empty text to
mutable paths.
=> setup: Allow creating files with empty content

.github/workflows/tests.yaml
There's a new GitHub Workflow that runs on every push, on every PR to `main`, and on-demand (via the GitHub GUI). This workflow comprises a series of steps to prepare, execute and report the Chisel unit tests. 
Along with the unit tests, a coverage report is also generated and uploaded to the GitHub workflow run, in HTML format. This coverage can, later on, be used to build additional tests to assert a minimum test coverage.
=> tests: add unit tests to the CI

cmd/chisel/cmd_help.go
Currently:
```bash
$ chisel help
Chisel can slice a Linux distribution using a release database
and construct a new filesystem using the finely defined parts.
Usage: chisel <command> [<options>...]
Commands can be classified as follows:
Basic: help, version
Action: slice
For more information about a command, run 'chisel help <command>'.
For a short summary of all commands, run 'chisel help --all'.
```
The text "  Action: slice" is wrong, and should be "  Action: cut".
This is fixed in this PR
=> fix: replace 'slice' by 'cut' in help information

.github/PULL_REQUEST_TEMPLATE.md
Just adding a PR template so that all new PRs contain a statement alluding to the contributor's conformity to our CLA.
=> Add PR template to remind contributors about the CLA

internal/deb/extract.go, internal/deb/extract_test.go
Permission bits passed to open(2) are AND-ed with current process umask.
Set umask to 0 at the beginning of extractData() and restore it at the
end, to extract files with desired permissions no matter what's the
current process umask.
How does dpkg do it? It invokes tar binary to extract data.tar.gz, and
tar sets current process umask to 0 if it's running as root. (See
--no-same-permissions in tar(1)).
Also fix expected permissions of /tmp from 01775 to 01777.
=> deb/extract: Extract with umask set to 0

internal/fsutil/create_test.go
We assume that umask is 002 in fsutil/create_test similarly to what
69ef992 ("deb/extract: Extract with umask set to 0") fixed. Set umask 0
for duration of the test.
-----
=> fsutil/create_test: Run with umask 0

internal/fsutil/create.go, internal/slicer/slicer_test.go
In the current code, a copyright file from a package is added to every
slice of that package. This went unnoticed because the file was silently
overwritten from successive slices of the same package. However, the
openssl's copyright file is a symlink to the libssl3's copyright file,
and creating a symlink on the same path for the second time fails. Fix
it by adding a copyright file to only the first slice of a package.
=> Handle duplicate symlink in multiple slices of a package

internal/scripts/scripts.go, internal/slicer/slicer.go, internal/slicer/slicer_test.go
-----
In commit 93353383 ("slicer: Allow listing implicit parent directories") we started recording path for checking if they can be read from scripts. The paths were recorded with slash for directories. But there was a bug because `filepath.Dir("/foo/") == "/foo"`. There were other issues as well. Fix the handling of paths in slicer and scripts.
=> slicer: Fix checking directory paths for listing

internal/testutil/reindent.go, internal/testutil/reindent_test.go, internal/testutil/testutil_test.go
Fix problem where the `Reindent` function would panic when an unindented first line was followed by a mix of indented and unindented lines such as the following.
```go
testutil.Reindent(`
a
b
c
`)
```
=> Fix `Reindent` on unindented inputs

internal/setup/setup_test.go
Archive structure is going to gain optional fields in followup commits. 
Change the structure definitions in setup_test.go to field:value format so
that new optional fields won't require extending the definition with zero
values.
Also format it with go fmt.
-----
=> Refactor setup_test.go

internal/archive/archive.go, internal/setup/setup.go, internal/setup/setup_test.go
Currently, we allow only a single archive named "ubuntu" to be defined in
chisel.yaml. Drop this restriction in preparation for the support of 
multiple archives.
When more than one archive is defined, one of them has to be specified as
the default one. When a slice definition file doesn't specify which archive
the sliced package belongs to, it is assumed it belongs to the default
archive.
This commit, in effect, doesn't change current behavior because we don't 
allow archives to define their URLs. It's only preparation for future 
commits that will add support for different types of archives.
-----
=> Drop single "ubuntu" archive restriction

LICENSE
Add a top-level license file (`LICENSE`).
---
Motivations for adding AGPL instead of GPL are the same as stated here: [Why the Affero GPL (gnu.org)](https://www.gnu.org/licenses/why-affero-gpl.html).
> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: **if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.**
> .
> .
> Suppose you develop and release a free program under the ordinary GNU GPL. If developer D modifies the program and releases it, the GPL requires him to distribute his version under the GPL too. Thus, if you get a copy of his version, you are free to …
=> feat: Add AGPLv3 license

.github/workflows/build.yml, cmd/mkversion.sh
Requires #90.
_(This PR includes commit 3e4ec0bf16911159b1a8da47aa32f423bb92701d from #90.)_
Create binaries on push, tag creation and when a release has been published. Create an archive with the binary, and attach it to the release if a release is published. Attach the archive in the workflow run as an artifact in all cases.
The [actions/checkout@v3](https://github.com/marketplace/actions/checkout) action overwrites annotated tag with lightweight tags breaking ``git describe``. See [1], [2]. This commit adds a workaround to restore the latest tag to it's original state.
References:
1. https://github.com/actions/checkout/issues/882
2. https://github.com/actions/checkout/issues/290
---
=> chore: create and attach binaries on tag, release

internal/archive/credentials.go, internal/archive/credentials_test.go, internal/archive/export_test.go
Add apt.auth.conf(5) machine credentials parser. See the parser code for 
documentation.
This commit doesn't change the current behavior. It's only a preparation 
for future commits that will add support for different types of archives.
This PR depends on #55.
-----
=> Add apt credentials parser

.github/workflows/snap.yml
Promote snap to `latest/candidate` channels upon every GitHub release.
Successfully executing this workflow job would require adding a `SNAPCRAFT_STORE_CREDENTIALS` secret in this repo. Please let me or @cjdcordeiro know if you don't have access to it (it's inside the credentials for the bot account).
_Similar to https://github.com/canonical/pebble/pull/255_.
Demo run: https://github.com/rebornplusplus/chisel/actions/runs/5925313450
_(not exactly the same behaviour as the demo promoted to `latest/beta` and ran the workflow job on `push`)_
-----
=> chore: promote snap to candidate on release

.github/workflows/snap.yml
In #94, the workflow for promoting snaps from latest/edge to latest/candidate upon GitHub release was introduced. We didn't have riscv64 builds for the snap back then. We have it now. [1]
This PR extends the promotion workflow for the riscv64 architecture.
References:
- [1] https://answers.launchpad.net/launchpad/+question/707699
=> chore: promote "riscv64" snap to candidate on release

internal/testutil/pkgdata.go, internal/testutil/pkgdata_test.go
MakeDeb() now expects that all provided tar entries have a non-empty
name. Otherwise it panics on array out of bounds access. Fix it.
We can create tarballs containing entries with empty name just fine. It
makes GNU tar fail when extracting, but it fails gracefully with
tar: Substituting `.' for empty member name
-rw-r--r-- root/root         0 1970-01-01 01:00
tar: .: Cannot open: File exists
tar: Exiting with failure status due to previous errors
=> testutil/pkgdata: Handle empty names in MakeDeb()

internal/slicer/slicer_test.go
Currently testArchive.Options() returns archive.Options with only the
Arch field set. In future we would like to extend testArchive to behave
differently based on its chisel.yaml definition.
Initialize archive.Options from setup.Release and store it in the
testArchive structure for each archive defined in chise.yaml.
=> slicer/test: Set archive options from release

tests/basic/task.yaml, tests/use-a-custom-chisel-release/task.yaml
Kinetic is EOL and its archive is gone and the tests fail. Drop it from
spread tests.
=> Switch from kinetic to focal in spread tests

README.md
-----
Adds 2 new badges:
- the snap badge, which also enables tracking via releases.juju.is
- the snap CI badge, for release events
=> docs: add snap and CI badges to README

internal/setup/setup.go, internal/setup/setup_test.go
-----
Ignoring extra fields makes the code forward compatible with changes in the yaml format, without a version bump being necessary.
=> bugfix: ignore extra fields in yaml

README.md
=> fix starlark link

tests/basic/task.yaml, tests/use-a-custom-chisel-release/task.yaml
-----
Up to now, the Spread tests were only running for the ubuntu-22.04 chisel release. 
This PR extends the spread variants, for each spread task, such that the tests run on all supported chisel releases
=> make Spread tests run for multiple chisel-releases

tests/basic/task.yaml
-----
The `libc6` contents' paths have changed in 24.04.
This PR adjusts the spread tests such that they accommodate that change.
This should fix the spread test errors in PRs like #116
=> fix(ci): adjust libc6 spread test for noble

internal/setup/setup.go, internal/setup/setup_test.go
This PR adds support for package names with a minimum length of two. Previously chisel only supported a minimum length of 3. The limit on the slice name is kept unchanged.
Fixes #119.
=> fix: package names can be of length two

.github/workflows/spread.yml, spread.yaml, tests/basic/task.yaml, tests/use-a-custom-chisel-release/task.yaml
Remove noble from the CI because the tests break too often. Will add them back when the release is stable.
-----
=> chore: add noble as separate github action

internal/deb/extract.go, internal/deb/extract_test.go, internal/setup/setup_test.go, internal/slicer/report.go, internal/slicer/slicer.go, internal/slicer/slicer_test.go, internal/testutil/permutation.go, internal/testutil/permutation_test.go
Due to several bugs and several limitations in the code, not all cases of selecting several slices of the same package worked. Specifically, we were not reporting the second slice correctly, which meant that the scripts could not select those paths. Additionally, there were several more problems when the slices had overlapping globs (which are valid in the same package). Mainly, the whole `until` calculation had to be redone, and the extractor had to be refactored to group by destination path, where before it was assuming there was only one.
-----
=> feat: support for several slices of the same package

go.mod, internal/deb/extract_test.go, internal/setup/setup.go, internal/slicer/slicer.go, snap/snapcraft.yaml, spread.yaml
-----
Streamline `slicer.go` moving all of the non essential functionality to self-contained function / abstractions and adding comments where necessary. Most importantly, combine all maps that recorded information about paths into one (`knownPaths`, `pathInfos` and `pathUntil`) and record the information in the same place instead of during several stages.
=> refactor: split slicer into steps and remove unnecessary state

internal/slicer/slicer.go, internal/slicer/slicer_test.go
Use ``strings.TrimPrefix()`` for relative paths instead of ``strings.TrimLeft()``, since ``TrimLeft`` takes in a cutset instead of a prefix sub-string.
In this particular case, if the ``--root`` (output) directory is ``/tmp/foo`` and we are determining the relative path for ``/tmp/foo/tmp-foo``, the relative path would result in ``/-foo`` since ``/tmp/foo/tmp`` would be matched by the ``/tmp/foo/`` cutset.
This results in a flawed map of ``knownPaths`` inside slicer.go, which is only checked by the mutation script functions such as ``content.list()``.
This commit fixes said bug.
=> hotfix: use strings.TrimPrefix() for relative paths

tests/basic/task.yaml
=> chore: update spread test to latest release changes

README.md, internal/setup/setup.go, internal/setup/setup_test.go
=> feat: parse generate property in sdf

internal/manifest/log.go, internal/manifest/manifest.go, internal/manifest/manifest_test.go, internal/manifest/suite_test.go
=> feat: internal manifest package

.github/workflows/build.yml
On release events, publish checksum of the binary tarballs that we already publish.
Closes #122.
=> chore: publish release checksums

internal/setup/setup.go, internal/setup/setup_test.go
=> refactor: tune error message for invalid generate value

internal/setup/setup.go, internal/setup/setup_test.go
Currently, the info command does not support the "generate" keyword in paths. This is a bug.
$ chisel info --release ubuntu-24.04 base-files_chisel
2024/10/07 08:47:57 Consulting release repository...
2024/10/07 08:47:57 Cached ubuntu-24.04 release is still up-to-date.
2024/10/07 08:47:57 Processing ubuntu-24.04 release...
error: internal error: unrecognised PathInfo type: generate
This PR fixes the said bug and adds support for "generate"-kind paths in the info command.
=> fix: info supports "generate" paths

cmd/chisel/cmd_info_test.go, internal/setup/setup.go, internal/setup/setup_test.go, internal/slicer/slicer_test.go
This commit depreciates support for the "chisel-v1" format in chisel. Notably the following fields/values are no longer supported:
- The "chisel-v1" value for top-level field "format". Use "v1"
instead.
- The "<archive>.v1-public-keys" field. Use "<archive>.public-keys"
instead.
- The top-level "v1-public-keys" field. Use "public-keys" instead.
BREAKING CHANGE: New versions of chisel which includes this commit will
no longer support the "chisel-v1" format in chisel-releases. Either
update the "chisel.yaml" file in chisel-releases or use a lower
version which does not have this commit.
-----
=> fix: deprecate "chisel-v1" format

internal/manifest/manifest.go, internal/manifest/manifest_test.go, internal/slicer/slicer_test.go
=> feat: validate manifest before writing

.github/workflows/security.yaml
-----
The current GH workflow runs the Trivy scan but doesn't react to its findings, exiting successfully even if there are vulnerabilities.
This PR adds an additional Trivy execution that raises an error on HIGH and CRITICAL vulnerabilities. It also uploads the vulnerability report to the CI run and the GitHub Security dashboard ([example](https://github.com/cjdcordeiro/chisel/security/code-scanning))
=> ci: report vulnerabilities and fail on HIGH,CRITICAL

cmd/chisel/cmd_info_test.go, internal/setup/setup.go, internal/setup/setup_test.go, internal/slicer/slicer_test.go
-----
This PR makes the `suites` attribute of archives in the `chisel.yaml` mandatory. All other attributes are already mandatory (version, components and keys).
There was an old fallback logic which would set `suites` to the release adjective if left unset, but this logic was only configured for 4 ubuntu releases, one of which (bionic) is no longer supported by chisel, and all other three have their suites properly configured in their `chisel.yaml` already, so this piece of logic never triggers ([focal](https://github.com/canonical/chisel-releases/blob/ubuntu-20.04/chisel.yaml), [jammy](https://github.com/canonical/chisel-releases/blob/ubuntu-22.04/chisel.yaml), [kinetic](https://github.com/canonical/chisel-releases/blob/ubuntu-22.10/chisel.yaml)).
=> feat: make suites mandatory in archive config

cmd/chisel/cmd_find_test.go, cmd/chisel/cmd_info_test.go, internal/setup/setup.go, internal/setup/setup_test.go, internal/slicer/slicer.go, internal/slicer/slicer_test.go, internal/testutil/archive.go
This commit adds support for fetching packages from multiple archives. It introduces a new field `archives.<archive-name>.priority` which takes in a signed integer and specifies the priority of a certain archive. A package is fetched from the archive with highest priority and negative priorities are ignored unless explicitly pinned in a package.
The concept of default archive in chisel.yaml is now deprecated. However, the field can still be present and it will be parsed but IGNORED.
DEPRECATED: "archives.<archive>.default" field in chisel.yaml.
-----
=> feat: support multiple archives with "priority" field

internal/deb/extract.go, internal/deb/extract_test.go, internal/fsutil/create.go, internal/fsutil/create_test.go, internal/slicer/slicer_test.go
-----
This commits introduces a new flag for `fsutil.Create` called `OverrideMode` which updates the mode of existing entries. It is used to ensure that the explicit folder overrides the permissions of the implicit ones.
=> bugfix: explicit parents override implicit

internal/slicer/slicer.go, internal/slicer/slicer_test.go
=> fix: remove implicit copyright installation

snap/snapcraft.yaml
Resolves #164.
Updates the snap description. _~~Uses the output from `chisel help --all` instead of `chisel --help` for details.~~_ Removes the usage from snap description.
=> snap: update description

internal/setup/setup_test.go, internal/setup/yaml.go, internal/slicer/slicer_test.go, tests/pro-archives/chisel-releases/chisel.yaml
"v2-archives" is used for backwards compatibility with Chisel <= 1.0.0 since it will be ignored. In new versions, it will be parsed with the new fields that break said compatibility, e.g. "pro" archives.
-----
=> feat: add support for "v2-archives" in "v1" format

internal/strdist/strdist.go
-----
Results of the benchmark on my machine (using hyperfine with 10 rounds):
```
$ bash benchmark.sh HEAD main 
Creating rev: e2ee603c7396b33038e47352c0722b5b1202fbfe (main)
Creating rev: 19829794e6454f78334c9a67b74d8abb9bc66b25 (HEAD)
Benchmark 1: ./19829794e6454f78334c9a67b74d8abb9bc66b25 info --release ../chisel-releases/ubuntu-24.04 'python3.12_core'
Time (mean ± σ):      5.341 s ±  0.115 s    [User: 5.528 s, System: 0.028 s]
Range (min … max):    5.239 s …  5.635 s    10 runs
Benchmark 2: ./e2ee603c7396b33038e47352c0722b5b1202fbfe info --release ../chisel-releases/ubuntu-24.04 'python3.12_core'
Time (mean ± σ):     18.366 s ±  0.139 s    [User: 19.677 s, System: 0.103 s]
Range (min … max):   18.219 s … 18.675 s    10 runs
Summary
./19829794e6454f78334c9a67b74d8abb9bc66b25 info …
```
=> feat: optimize common case of GlobPath

snap/snapcraft.yaml
-----
Simple renaming of the `system-files` interface, following the suggestion from https://forum.snapcraft.io/t/request-auto-connection-for-system-files-in-chisel/44542/2?u=cjdc
=> chore(snap): rename system-files interface

.github/workflows/build.yml, .github/workflows/snap.yml, .github/workflows/tests.yaml
-----
Bumps `upload-artifact` and `download-artifact` actions to `v4`, as `v3` is deprecated.
Associated workflow run: https://github.com/canonical/chisel/actions/runs/12812400771/job/35723950707?pr=192#step:1:36
Ref: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore(ci): bump artifact actions to v4

.github/workflows/lint.yaml, go.mod, internal/manifestutil/manifestutil.go, internal/setup/yaml.go, snap/snapcraft.yaml
-----
- This PR bumps the Golang version to 1.22 to fix the known exploited vulnerabilities (CVE-2024-34158 and CVE-2024-34156, and CVE-2024-34155, which is a medium vulnerability not listed as a KEV) in Golang v1.21.
- To accommodate the bumped Golang version, the [golangci-lint](https://github.com/golangci/golangci-lint) is bumped to `v1.63.4`.
- The PR bumping Golang to v1.23 #198 is dropped since the latest Ubuntu LTS (noble) does not officially support v1.23, which resulted in additional changes in building and testing the project.
=> chore(deps,build,ci): bump Golang to v1.22

internal/deb/extract.go, internal/deb/extract_test.go, internal/fsutil/create.go, internal/fsutil/create_test.go, internal/scripts/scripts.go, internal/setup/fetch.go, internal/slicer/slicer.go, internal/slicer/slicer_test.go
-----
This commits adds several security controls and tests so that files
cannot be extracted outside of the target directory, and hardlinks
cannot point to files outside of the target directory.
=> feat: cannot extract files outside the target directory

internal/scripts/scripts.go, internal/scripts/scripts_test.go
TopLevelControl was disabled accidentally on #211. The old Starlark API had it enabled by default and the new one does not.
-----
Bug found on chisel-releases CI when testing all packages against main ([action failure](https://github.com/canonical/chisel-releases/actions/runs/14238222496/job/39901906231?pr=509#step:8:1157)).
=> bugfix: revert disabling TopLevelControl

internal/scripts/scripts.go, internal/scripts/scripts_test.go
Solves #221.
In the future we might want to have more extensive testing when setting the root to be "/" but the setup per test is complex as we would be polluting the system running the test itself (`chroot` with overlays might be an option). The complexity here would only make sense if justified with more of these bugs.
-----
=> fix: script errors when root is /

cmd/chisel/cmd_debug_check_release_archives.go, cmd/chisel/cmd_debug_check_release_archives_test.go, tests/debug-check-release-archives/task.yaml
If an implicit conflict is found in the release but it is handled in the slice definition then we do not consider it an error and the command does not fail.
-----
=> feat: check if implicit conflict is handled in slice definitions

.github/workflows/lint.yaml, cmd/chisel/cmd_info.go, go.mod, go.sum, snap/snapcraft.yaml
-----
The minimal required Go version is bumped to `1.24.6` to fix [GO-2025-3956](https://pkg.go.dev/vuln/GO-2025-3956)/[CVE-2025-47906](https://www.cve.org/CVERecord?id=CVE-2025-47906). The Go version `1.23.12` cannot be used due to the unavailability in the snapstore.
The version of package `github.com/ulikunitz/xz` is bumped to `v0.5.15` to fix [GO-2025-3922](https://pkg.go.dev/vuln/GO-2025-3922)/[CVE-2025-58058](https://www.cve.org/CVERecord?id=CVE-2025-58058).
A complete `govulncheck` before the fix goes as follows:
```
=== Symbol Results ===
Vulnerability #1: GO-2025-3956
Unexpected paths returned from LookPath in os/exec
More info: https://pkg.go.dev/vuln/GO-2025-3956
Standard library
Found in: os/exec@go1.24.4
Fixed in: os/exec@go1.24.6
Example traces found:
#1: …
```
=> chore: bump versions to fix CVE

.github/workflows/tiobe.yaml
-----
This PR introduces scheduled CI runs for the Tiobe TiCS static code analysis. A future PR may repurpose this workflow to also run on PRs, offering quality review gate (this is pending on work from Tiobe).
This workflow has been tested here: https://github.com/canonical/chisel-copy/actions/runs/17854511904
=> ci: add scheduled tics code analysis workflows  

cmd/chisel/cmd_cut.go
-----
Allows passing multiple `--ignore` flags, for example `chisel cut --release=./ --root=rootfs --ignore=unmaintained --ignore=unstable` libc6_libs`.
Proposal for addressing [this](https://github.com/canonical/chisel-releases/pull/676) issue/PR in chisel-releases.
TLDR; in `chisel-releases` cli we want a general cut command which will try to cut both unmaintained and unstable releases (at the time of writing this is 20.04 and 25.10 respectively). As opposed to figuring out the logic dynamically we could just always pass all the ignore flags.
I would also argue that this is the intuitive behavior users would expect + allows us to trivially expand into any future conditions we might want to ignore.
=> feat: allow multiple ignores
